### ISSUE TITLE
有没有人会解决这个

### ISSUE THREAD

**Issue by headmaster0305** [jiayingwu19/SheepDog#1]
![image](https://github.com/user-attachments/assets/15ab1854-7934-4f62-8a47-7a44c78f4797)

**Comment by jiayingwu19** [comment]
你好，我查看了本仓库，确认文件路径 `data/news_articles/politifact_train.pkl` 是存在的。

根据你的报错信息，问题可能与代码运行时的 current working directory 设置有关，而不是仓库本身的问题。建议你检查当前的 current working directory 是否设置正确。

感谢你对我们工作的关注。
